// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package db

import (
	"github.com/jackc/pgx/v5/pgtype"
)

type Environment struct {
	// Primary key and unique ID for an environment in the system.
	ID pgtype.UUID
	// Preferred name to display when referencing this user, free text could be a real name, partial name, nickname etc.
	Name string
}
