// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const countEnvironments = `-- name: CountEnvironments :one
SELECT COUNT(*) FROM environments
`

func (q *Queries) CountEnvironments(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countEnvironments)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT
    id, name
FROM environments
WHERE
    name = $1
`

func (q *Queries) GetEnvironmentByName(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, name)
	var i Environment
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const listEnvironments = `-- name: ListEnvironments :many
SELECT id, name
FROM environments
ORDER BY name ASC
LIMIT $1
OFFSET $2
`

type ListEnvironmentsParams struct {
	Limit  int32
	Offset int32
}

func (q *Queries) ListEnvironments(ctx context.Context, arg ListEnvironmentsParams) ([]Environment, error) {
	rows, err := q.db.Query(ctx, listEnvironments, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Environment
	for rows.Next() {
		var i Environment
		if err := rows.Scan(&i.ID, &i.Name); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertEnvironment = `-- name: UpsertEnvironment :one
INSERT INTO environments (id, name)
VALUES ($1, $2)
ON CONFLICT (id) DO UPDATE SET name = EXCLUDED.name
RETURNING id, name
`

type UpsertEnvironmentParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) UpsertEnvironment(ctx context.Context, arg UpsertEnvironmentParams) (Environment, error) {
	row := q.db.QueryRow(ctx, upsertEnvironment, arg.ID, arg.Name)
	var i Environment
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}
