// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: queries.sql

package db

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const getEnvironmentByName = `-- name: GetEnvironmentByName :one
SELECT 
    id, name
FROM environments
WHERE
    name = $1
`

func (q *Queries) GetEnvironmentByName(ctx context.Context, name string) (Environment, error) {
	row := q.db.QueryRow(ctx, getEnvironmentByName, name)
	var i Environment
	err := row.Scan(&i.ID, &i.Name)
	return i, err
}

const insertEnvironment = `-- name: InsertEnvironment :exec
INSERT INTO environments (id, name)
VALUES ($1, $2)
`

type InsertEnvironmentParams struct {
	ID   pgtype.UUID
	Name string
}

func (q *Queries) InsertEnvironment(ctx context.Context, arg InsertEnvironmentParams) error {
	_, err := q.db.Exec(ctx, insertEnvironment, arg.ID, arg.Name)
	return err
}
